INSERT INTO USERS (ID, USERNAME,PASSWORD) VALUES (1, 'ADMIN@NOKIA.COM', '$2A$08$FL7U5XCVSZL78SU29X1TI.DXI.9RYO8T0Q5WK2ROJ.1CDR53BMAVG');

INSERT INTO APP_USER (USER_ID, USER_NAME, ENCRYTED_PASSWORD, ENABLED) 
VALUES (2, 'DBUSER1', '$2a$10$Luz5MPYfXbACxJqyxFpsn.iDpMyVzbt6JDT4mw8DAaLlAnbgC4zdS', 1);

INSERT INTO APP_USER (USER_ID, USER_NAME, ENCRYTED_PASSWORD, ENABLED)
VALUES (1, 'DBADMIN1', '$2a$10$Luz5MPYfXbACxJqyxFpsn.iDpMyVzbt6JDT4mw8DAaLlAnbgC4zdS', 1);
 

INSERT INTO APP_ROLE (ROLE_ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO APP_ROLE (ROLE_ID, ROLE_NAME) VALUES (2, 'ROLE_USER');
 
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID) VALUES (1, 1, 1);
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID) VALUES (2, 1, 2);
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID) VALUES (3, 2, 2);
