server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://auth-server:9000
        registration:
          api-client-authorization-code:
            authorization-grant-type: authorization_code
            client-id: api-client
            client-name: api-client-authorization-code
            client-secret: secret
            provider: spring
            redirect-uri: http://127.0.0.1:8080/authorized
            scope: api.read
          api-client-oidc:
            authorization-grant-type: authorization_code
            client-id: api-cilent
            client-name: api-client-oidc
            client-secret: secret
            provider: spring
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/{registrationId}
            scope: openid
